create table PLAYERSTATS(
G       		NUMBER (4),
GS       		NUMBER(5),
MP        		NUMBER(10),
PTS 			NUMBER(5),
TSPER			NUMBER(5),
FTM				NUMBER(5),
FTA 			NUMBER(5),
FTPER			NUMBER(5),
FGM				NUMBER(5),	
FGA				NUMBER(5),
FGPER			NUMBER(5),
THREE			NUMBER(5),
THREEPA			NUMBER(5),
THREEPPER		NUMBER(5),
TWOPM			NUMBER(5),
TWOPA			NUMBER(5),
TWOPER			NUMBER(5),
OREB			NUMBER(5),
OREBPER			NUMBER(5),
DREB			NUMBER(5),
DREBPER			NUMBER(5),
TREB			NUMBER(5),
TREBPER			NUMBER(5),	
AST				NUMBER(5),
ASTPER			NUMBER(5),
STL				NUMBER(5),
STLPER			NUMBER(5),
BLK				NUMBER(5),
BLKPER			NUMBER(5),
TOV 			NUMBER(5),
TOVPER			NUMBER(5),
USGPER			NUMBER(5),
OFFWS			NUMBER(5),	
DEFWS			NUMBER(5),
WS				NUMBER(5),
WS1				NUMBER(5),
BPM				NUMBER(5),
VORP			NUMBER(5),
EFGPER			NUMBER(5),
PF              NUMBER(5),
PLAYERPERFOMANCE_ID NUMBER(7) NOT NULL ,
PERPLAYERID        NUMBER(5) NOT NULL ,
CONSTRAINT  PK_PLAYERSTATS PRIMARY KEY (PLAYERPERFOMANCE_ID)
);


create table PLAYER(
PLAYERID  	NUMBER(5) NOT NULL,
PLAYERNAME 	VARCHAR(50),
AGE      	NUMBER(5) NOT NULL CHECK (AGE>18 AND AGE <=60),
teamID		NUMBER(5) NOT NULL ,
CONSTRAINT pri_player PRIMARY KEY (PLAYERID)
);


alter table PLAYERSTATS
ADD CONSTRAINT fk_pal FOREIGN KEY (PERPLAYERID) REFERENCES PLAYER(PLAYERID);







create table possittion(
POS varchar(10),
POSplayerId NUMBER(5) NOT NULL,
CONSTRAINT prima_key PRIMARY KEY (POS, POSplayerId),
CONSTRAINT FK_PLAYER_POSSITION FOREIGN KEY (POSplayerId) REFERENCES PLAYER(PLAYERID)
);


create table previewsTeam(
POS varchar(10),
POSTEAMIDD VARCHAR(10) NOT NULL ,
PLAYER_ID NUMBER(5) NOT NULL  ,
CONSTRAINT prim_key PRIMARY KEY (PLAYER_ID,POSTEAMIDD), 
CONSTRAINT FK_PREVPLAYER_POSSITION FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYERID)
);
-- tha kano mia paradoxi edo oti o sindiasmos aftos einai monadikos


 

create table team(
teamID 		NUMBER(5) NOT NULL,
teamName	varchar(50),
teamAcro	VARCHAR(10),
location	VARCHAR(50),
Arena 		VARCHAR(50),
CONSTRAINT pr_key PRIMARY KEY (teamID)
);





ALTER TABLE PLAYER
ADD(
CONSTRAINT FK_MATCH4 FOREIGN KEY (teamID) REFERENCES TEAM(teamID)	
);



ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-YYYY';

CREATE TABLE MATCH(
GAME_ID   			NUMBER(5) NOT NULL,
TEAM1     			NUMBER(5) NOT NULL ,
TEAM2	  			NUMBER(5) NOT NULL ,
team1Points 		NUMBER(3) ,	
team2Points			NUMBER(3),	
home_awawy			VARCHAR(5),
dateMatch			DATE,
referee				VARCHAR(40),
winOrLose			VARCHAR(4),
MATCHPEROMANCEID    NUMBER(4),
CONSTRAINT FK_TEAM1_PART FOREIGN KEY (TEAM1) REFERENCES TEAM(teamID),
CONSTRAINT FK_TEAM2_PART FOREIGN KEY (TEAM2) REFERENCES TEAM(teamID),
CONSTRAINT priK_key PRIMARY KEY (GAME_ID)
);

create table takeParthsin(
TEAMID  NUMBER(5) NOT NULL,
GAMEID 	NUMBER(5) NOT NULL,
CONSTRAINT primaryT_key PRIMARY KEY(TEAMID,GAMEID),
CONSTRAINT FK1_TAKE_PART FOREIGN KEY (TEAMID) REFERENCES TEAM(teamID),
CONSTRAINT FK5_TAKE_PARTI FOREIGN KEY (GAMEID) REFERENCES MATCH(GAME_ID)
);


CREATE TABLE  MATCHPEROMANCE_ID(
MATCHPEROMANCEID  		NUMBER(4) NOT NULL,
FIELDGOALSATTEMED 		NUMBER(5),
FIELDGOALSPERSENT 		NUMBER(5),
X3POINTSSHOOTS   		NUMBER(5),
X3POINTSSHOOTSATTEMPED	NUMBER(5),
X3POINTSHHOTPERSENT  	NUMBER(5),
FREETHROWS 				NUMBER(5),
FREETHROWSATTEMED      	NUMBER(5),
FREETHROWPERSENET 		NUMBER(5),
OFFREBOUNDS				NUMBER(5),
TOTALREBOUNDS			NUMBER(5),
ASSISTS					NUMBER(5),
STEAL 					NUMBER(5),
BLOCKS 					NUMBER(5),
TURNOVERS				NUMBER(5),
TOTALFOULS				NUMBER(5),
OPP_FIELD_GOALS			NUMBER(5),
OPP_FIELDGOLASATTEMED	NUMBER(5),
OPP_FIELDGOLASATTEMEDPERSENT NUMBER(5),
OPP_3POINTSSHOOTS 			NUMBER(5),
OPP_3POINTSSHOOTSATTEMED	NUMBER(5),
OPP_3POINTSHHOTSPERSENET	NUMBER(5),
OPP_FREETHROWS			NUMBER(5),
OPP_FREETHROWSATTEMED	NUMBER(5),
OPP_FREETHROSPERNSET	NUMBER(5),
OPP_OFFREBOUNDS			NUMBER(5),
OPP_TOTALREBOUND		NUMBER(5),
OPP_ASSSISTS			NUMBER(5),
OPP_BLOCKS 				NUMBER(5),
OPP_TURNOVERS			NUMBER(5),
OPP_TOTALFOULS			NUMBER(5),
CONSTRAINT mPRI_key  PRIMARY KEY(MATCHPEROMANCEID)
);



ALTER TABLE MATCH
ADD(
CONSTRAINT FK_MATCH9 FOREIGN KEY (MATCHPEROMANCEID) REFERENCES MATCHPEROMANCE_ID(MATCHPEROMANCEID)	
);
