DROP TABLE MATCH CASCADE CONSTRAINTS;
DROP TABLE MATCHPEROMANCE_ID CASCADE CONSTRAINTS;
DROP TABLE team CASCADE CONSTRAINTS;
DROP TABLE previewsTeam CASCADE CONSTRAINTS;
DROP TABLE possittion CASCADE CONSTRAINTS;
DROP TABLE PLAYER CASCADE CONSTRAINTS;
DROP TABLE PLAYERSTATS CASCADE CONSTRAINTS;
DROP TABLE takeParthsin CASCADE CONSTRAINTS;